<a href="https://colab.research.google.com/github/asilbek-data-scientist/1_Modul/blob/main/2_modul_Numpy_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Indeks va kesib olish usullari

In [2]:
import numpy as np

In [3]:
arr = np.arange(10, 100, 5)
arr

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

In [4]:
arr.ndim

1

In [5]:
arr.shape

(18,)

In [6]:
arr.size

18

In [7]:
arr.dtype

dtype('int64')

In [8]:
arr_float = arr.astype(np.float64)
arr_float

array([10., 15., 20., 25., 30., 35., 40., 45., 50., 55., 60., 65., 70.,
       75., 80., 85., 90., 95.])

In [9]:
arr

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

In [10]:
arr[3:6]

array([25, 30, 35])

In [11]:
arr_sliced = arr[3:6]
arr_sliced[:] = 0
arr_sliced

array([0, 0, 0])

In [12]:
arr2 = np.arange(10, 100, 10)
arr2

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [13]:
sliced_arr2 = arr2[4:7].copy()
sliced_arr2

array([50, 60, 70])

In [14]:
sliced_arr2[:] = 0
sliced_arr2

array([0, 0, 0])

In [15]:
arr2

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

Ikki o'lchamli massivlarni bitta elementlarini kesib olish

In [16]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
arr2d.dtype

dtype('int64')

In [18]:
arr2d.ndim

2

In [19]:
arr_4 = arr2d[1,0]
arr_4

4

In [20]:
arr_8 = arr2d[2,1]
arr_8 = 0

In [21]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
arr2d_8 = arr2d[1, 0:3]
arr2d_8

array([4, 5, 6])

In [23]:
arr3d = np.arange(27).reshape(((3, 3, 3)))
arr3d

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [24]:
arr4d = np.arange(18).reshape(((2, 3, 3)))
arr4d

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

In [25]:
arr3d[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [26]:
arr3d[1][1:,1:]

array([[13, 14],
       [16, 17]])

In [27]:
# Ismlar
names = np.array(['Hasan', 'Husan', 'Mirzabek', 'Elyor', 'Hasan', 'Javohir', 'Elyor'])
names

array(['Hasan', 'Husan', 'Mirzabek', 'Elyor', 'Hasan', 'Javohir', 'Elyor'],
      dtype='<U8')

In [53]:
# data
data = np.random.randn(7,4)
data

array([[ 0.2793797 , -0.47134043,  1.23942332, -1.29230485],
       [-0.59732594,  0.25397309,  0.24335962,  0.31273898],
       [ 0.60890865, -0.4785903 ,  0.99339083,  1.30281136],
       [-0.78555995, -0.87610634,  1.95288561,  1.28405997],
       [-0.97609241,  0.1407985 , -0.19951321,  0.68541071],
       [ 1.08275194,  1.73443104, -1.28311387, -0.68728156],
       [ 0.13174432,  0.76141145, -1.45108107,  1.26450581]])

In [54]:
names == "Hasan"

array([ True, False, False, False,  True, False, False])

In [55]:
data[names == "Hasan"] # Hasanga tegishli barcha malumotlarni kesib olish.

array([[ 0.2793797 , -0.47134043,  1.23942332, -1.29230485],
       [-0.97609241,  0.1407985 , -0.19951321,  0.68541071]])

In [56]:
names == "Elyor"

array([False, False, False,  True, False, False,  True])

In [57]:
data[names == "Elyor"] # Elyorga tegishli barcha mal'umotlarni kesib olish.

array([[-0.78555995, -0.87610634,  1.95288561,  1.28405997],
       [ 0.13174432,  0.76141145, -1.45108107,  1.26450581]])

In [58]:
names == "Mirzabek"

array([False, False,  True, False, False, False, False])

In [59]:
data[names == "Mirzabek"] #Mirzabekga tegishli barcha malumotlarni kesib olish.

array([[ 0.60890865, -0.4785903 ,  0.99339083,  1.30281136]])

In [60]:
data[names == "Mirzabek", 1:2] #Mizrabekga tegishli bitta malumotni kesib olish.

array([[-0.4785903]])

In [61]:
names != 'Hasan'

array([False,  True,  True,  True, False,  True,  True])

In [62]:
data[names != 'Hasan']

array([[-0.59732594,  0.25397309,  0.24335962,  0.31273898],
       [ 0.60890865, -0.4785903 ,  0.99339083,  1.30281136],
       [-0.78555995, -0.87610634,  1.95288561,  1.28405997],
       [ 1.08275194,  1.73443104, -1.28311387, -0.68728156],
       [ 0.13174432,  0.76141145, -1.45108107,  1.26450581]])

In [63]:
data[~(names == 'Hasan')]

array([[-0.59732594,  0.25397309,  0.24335962,  0.31273898],
       [ 0.60890865, -0.4785903 ,  0.99339083,  1.30281136],
       [-0.78555995, -0.87610634,  1.95288561,  1.28405997],
       [ 1.08275194,  1.73443104, -1.28311387, -0.68728156],
       [ 0.13174432,  0.76141145, -1.45108107,  1.26450581]])

In [64]:
names

array(['Hasan', 'Husan', 'Mirzabek', 'Elyor', 'Hasan', 'Javohir', 'Elyor'],
      dtype='<U8')

In [65]:
mask = (names == 'Hasan') | (names == 'Husan')
mask

array([ True,  True, False, False,  True, False, False])

In [66]:
data[mask]

array([[ 0.2793797 , -0.47134043,  1.23942332, -1.29230485],
       [-0.59732594,  0.25397309,  0.24335962,  0.31273898],
       [-0.97609241,  0.1407985 , -0.19951321,  0.68541071]])

In [67]:
data

array([[ 0.2793797 , -0.47134043,  1.23942332, -1.29230485],
       [-0.59732594,  0.25397309,  0.24335962,  0.31273898],
       [ 0.60890865, -0.4785903 ,  0.99339083,  1.30281136],
       [-0.78555995, -0.87610634,  1.95288561,  1.28405997],
       [-0.97609241,  0.1407985 , -0.19951321,  0.68541071],
       [ 1.08275194,  1.73443104, -1.28311387, -0.68728156],
       [ 0.13174432,  0.76141145, -1.45108107,  1.26450581]])

In [68]:
data[data<0]=0
data

array([[0.2793797 , 0.        , 1.23942332, 0.        ],
       [0.        , 0.25397309, 0.24335962, 0.31273898],
       [0.60890865, 0.        , 0.99339083, 1.30281136],
       [0.        , 0.        , 1.95288561, 1.28405997],
       [0.        , 0.1407985 , 0.        , 0.68541071],
       [1.08275194, 1.73443104, 0.        , 0.        ],
       [0.13174432, 0.76141145, 0.        , 1.26450581]])

In [69]:
data[data>1] = 1
data

array([[0.2793797 , 0.        , 1.        , 0.        ],
       [0.        , 0.25397309, 0.24335962, 0.31273898],
       [0.60890865, 0.        , 0.99339083, 1.        ],
       [0.        , 0.        , 1.        , 1.        ],
       [0.        , 0.1407985 , 0.        , 0.68541071],
       [1.        , 1.        , 0.        , 0.        ],
       [0.13174432, 0.76141145, 0.        , 1.        ]])