<a href="https://colab.research.google.com/github/asilbek-data-scientist/1_Modul/blob/main/2_modul_Numpy_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Universal funksiyalar

    sqrt, square, exp, log, modf, sign, isnan funksiyalarini ko'rib chiqamiz.

In [2]:
import numpy as np

In [3]:
arr = np.arange(10)

In [4]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [5]:
np.square(arr)

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [6]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [8]:
np.log(arr[1:])

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [11]:
arr1 = np.random.randn(6) # 6 ta elementdan iborat taxminiy qiymatlarga ega massiv
arr1

array([-2.10232228, -0.6094089 , -1.37465471, -0.40305571, -0.0365181 ,
       -0.10970545])

In [13]:
qoldiq, butun = np.modf(arr1) # arr1 ning elementlarini qoldiq va butun qismlarini ikkita massivga ajratib beradi.

In [14]:
print(qoldiq)
print(butun)

[-0.10232228 -0.6094089  -0.37465471 -0.40305571 -0.0365181  -0.10970545]
[-2. -0. -1. -0. -0. -0.]


In [17]:
np.sign(arr1) # arr1 massivning elementlari ishoralarini "-1" va "1" larni qaytaradi.

array([-1., -1., -1., -1., -1., -1.])

isnan massivning elementlarida NaN ma'lumoti bo'lsa True qaytaradi va aksincha esa  False qaytaradi.

In [18]:
arr1

array([-2.10232228, -0.6094089 , -1.37465471, -0.40305571, -0.0365181 ,
       -0.10970545])

In [19]:
np.isnan(arr1)

array([False, False, False, False, False, False])

In [21]:
arr1[0] = np.NaN

In [22]:
np.isnan(arr1)

array([ True, False, False, False, False, False])

Binary funksiyalari (ikkita argument qabul qiluvchi funksiya)

  add, multiply, maximum funksiyalarini ko'rib chiqamiz.

In [23]:
arr2 = np.random.randn(6)
arr2

array([-1.36901753,  0.50403759,  1.80717535, -0.57055387, -1.5993494 ,
        1.00066155])

In [32]:
arr3 = np.random.randn(6)
arr3

array([0.66437012, 0.4722141 , 1.81774735, 1.00232113, 0.3240033 ,
       0.1116997 ])

In [33]:
np.add(arr2, arr3) # arr2 va arr3 ning elementlarini mos ravishda qo'shib beradi.

array([-0.70464741,  0.9762517 ,  3.62492269,  0.43176726, -1.2753461 ,
        1.11236125])

In [34]:
arr2 + arr3

array([-0.70464741,  0.9762517 ,  3.62492269,  0.43176726, -1.2753461 ,
        1.11236125])

In [35]:
np.multiply(arr2, arr3) # ikkita mos ravishda teng bo'lgan elementlarni ko'paytirib beradi.

array([-0.90953434,  0.23801366,  3.28498819, -0.5718782 , -0.51819449,
        0.1117736 ])

In [41]:
np.maximum(arr2, arr3)

array([0.66437012, 0.50403759, 1.81774735, 1.00232113, 0.3240033 ,
       1.00066155])

In [40]:
arr2

array([-1.36901753,  0.50403759,  1.80717535, -0.57055387, -1.5993494 ,
        1.00066155])

In [39]:
arr3

array([0.66437012, 0.4722141 , 1.81774735, 1.00232113, 0.3240033 ,
       0.1116997 ])