<a href="https://colab.research.google.com/github/asilbek-data-scientist/1_Modul/blob/main/2_modul_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy kutubxonasini chaqirib olish.

In [1]:
import numpy as np

Python list bn Numpy kutubxoxnasidagi massivelar(arraylar) orasidagi farqni ko'ramiz.

In [2]:
my_list = list(range(100000)) # python list 0-99999 -->normal 
my_array = np.array(range(100000)) # numpy array (massive) --> vektorlashgan

In [3]:
%time for _ in range(10): [x*2 for x in my_list] #normal

CPU times: user 91 ms, sys: 14.6 ms, total: 106 ms
Wall time: 108 ms


In [4]:
%time for _ in range(10): 2*my_array #vektorlashgan

CPU times: user 3.01 ms, sys: 224 µs, total: 3.23 ms
Wall time: 5.12 ms


vektorlashgan usulda 20 marta tezroq ishlaydi

In [5]:
65.7/3.15

20.857142857142858

Numpyda massiv yaratishning eng oson yo'llaridan biri bu 'array' funksiyasi yordamida amalga oshiriladi. Ushbu funksiya har qanday turdagi ketma-ket ma'lumotlarni qabul qilib, uni yangi Numpy arrayiga o'girib beradi.

In [6]:
data1 = [3.5, 5, 6, 2] #list
arr1 = np.array(data1) #array1

In [7]:
arr1

array([3.5, 5. , 6. , 2. ])

In [26]:
type(arr1)

numpy.ndarray

In [8]:
data2 = (4, 6, 7.8, 18) #tuple
arr2 = np.array(data2)
arr2

array([ 4. ,  6. ,  7.8, 18. ])

Massiv o'lchami

In [9]:
arr1.ndim #array1 ning massiv o'lchami

1

In [10]:
arr2.ndim #array2 ning massiv o'lchami

1

ikki va undan katta o'lchmli massivlar

In [11]:
data3 = [[1, 2, 3, 4], [5,6,7,8]] #list ichidagi list (nested list)
arr3 = np.array(data3)
arr3

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [12]:
arr3.ndim

2

In [13]:
data4 = [[[1,2,3,],[4,5,6,],[7,8,9]]]
arr4 = np.array(data4)
arr4

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [14]:
arr4.ndim

3

shape, size metodalari
  - shape metodi massivning qatorlari sonini, size massivdagi elementlar sonini ko'rsatadi. (q, u)

In [15]:
arr4

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [16]:
arr4.shape

(1, 3, 3)

In [17]:
arr3.shape # shape qaator va ustunlar sonini ko'rsatadi.

(2, 4)

In [18]:
arr3

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [19]:
arr3.size # size massivdagi elementlar sonini ko'rsatadi.

8

zeros va ones massivelarini yaratish.

In [20]:
arr_zeros = np.zeros((2, 4)) # barcha elementlari nolga teng massivlar yaratadi.
arr_zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [21]:
arr_ones = np.ones((2, 3, 5))
arr_ones

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [22]:
arr6 = np.arange(4, 30, 2) #4 dan 30 gacha qiymatlarni 2 qadam massivga joylab beradi.
arr6

array([ 4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [23]:
arr_6 = np.arange(20) # default bo'lganda start=0 qadam=1 hisoblanadi.
arr_6

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

Massivlar yaratishda malumot turlarini aniq kiritish, malumot turlarini aniqlash, bir turdagiikkinchi turdagi malumot turiga o'grirish

In [29]:
arr5 = np.array([1, 2, 3], dtype=np.float64)
arr5

array([1., 2., 3.])

In [30]:
arr7 = np.array([4, 5, 6], dtype=np.int32)
arr7

array([4, 5, 6], dtype=int32)

In [33]:
arr5.dtype

dtype('float64')

In [34]:
arr5.size

3

In [35]:
arr8 = np.array([1, 2, 3, 4]) #defaultda int64 qabul qiladi.
arr8

array([1, 2, 3, 4])

In [36]:
arr8.dtype

dtype('int64')

In [38]:
float_arr8 = arr8.astype(np.float64)
float_arr8

array([1., 2., 3., 4.])

In [39]:
float_arr8.dtype

dtype('float64')

In [40]:
data1 = np.array([2.4, 5, 6.7, 9])
data1

array([2.4, 5. , 6.7, 9. ])

In [41]:
data1.dtype

dtype('float64')

In [43]:
data1.ndim

1

In [44]:
data1.size

4

In [45]:
data1.shape

(4,)

In [48]:
int_data1 = data1.astype(np.int64)
int_data1

array([2, 5, 6, 9])