<a href="https://colab.research.google.com/github/asilbek-data-scientist/1_Modul/blob/main/2_modul_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy kutubxonasini chaqirib olish.

In [7]:
import numpy as np

Python list bn Numpy kutubxoxnasidagi massivelar(arraylar) orasidagi farqni ko'ramiz.

In [3]:
my_list = list(range(100000)) # python list 0-99999 -->normal 
my_array = np.array(range(100000)) # numpy array (massive) --> vektorlashgan

In [4]:
%time for _ in range(10): [x*2 for x in my_list] #normal

CPU times: user 61.8 ms, sys: 5.73 ms, total: 67.5 ms
Wall time: 67.4 ms


In [5]:
%time for _ in range(10): 2*my_array #vektorlashgan

CPU times: user 1.83 ms, sys: 976 µs, total: 2.81 ms
Wall time: 6.01 ms


vektorlashgan usulda 20 marta tezroq ishlaydi

In [6]:
65.7/3.15

20.857142857142858

Numpyda massiv yaratishning eng oson yo'llaridan biri bu 'array' funksiyasi yordamida amalga oshiriladi. Ushbu funksiya har qanday turdagi ketma-ket ma'lumotlarni qabul qilib, uni yangi Numpy arrayiga o'girib beradi.

In [8]:
data1 = [3.5, 5, 6, 2] #list
arr1 = np.array(data1) #array1

In [9]:
arr1

array([3.5, 5. , 6. , 2. ])

In [10]:
data2 = (4, 6, 7.8, 18) #tuple
arr2 = np.array(data2)
arr2

array([ 4. ,  6. ,  7.8, 18. ])

Massiv o'lchami

In [11]:
arr1.ndim #array1 ning massiv o'lchami

1

In [12]:
arr2.ndim #array2 ning massiv o'lchami

1

ikki va undan katta o'lchmli massivlar

In [13]:
data3 = [[1, 2, 3, 4], [5,6,7,8]] #list ichidagi list (nested list)
arr3 = np.array(data3)
arr3

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [14]:
arr3.ndim

2

In [18]:
data4 = [[[1,2,3,],[4,5,6,],[7,8,9]]]
arr4 = np.array(data4)
arr4

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [19]:
arr4.ndim

3

shape, size metodalari
  - shape metodi massivning qatorlari sonini, size massivdagi elementlar sonini ko'rsatadi. (q, u)

In [36]:
arr4

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [21]:
arr4.shape

(1, 3, 3)

In [26]:
arr3.shape # shape qaator va ustunlar sonini ko'rsatadi.

(2, 4)

In [25]:
arr3

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [27]:
arr3.size # size massivdagi elementlar sonini ko'rsatadi.

8

zeros va ones massivelarini yaratish.

In [29]:
arr_zeros = np.zeros((2, 4)) # barcha elementlari nolga teng massivlar yaratadi.
arr_zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [30]:
arr_ones = np.ones((2, 3, 5))
arr_ones

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [33]:
arr6 = np.arange(4, 30, 2) #4 dan 30 gacha qiymatlarni 2 qadam massivga joylab beradi.
arr6

array([ 4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [35]:
arr_6 = np.arange(20) # default bo'lganda start=0 qadam=1 hisoblanadi.
arr_6

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])