<a href="https://colab.research.google.com/github/asilbek-data-scientist/1_Modul/blob/main/2_modul_Numpy_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Universal funksiyalar

    sqrt, square, exp, log, modf, sign, isnan funksiyalarini ko'rib chiqamiz.

In [2]:
import numpy as np

In [3]:
arr = np.arange(10)

In [4]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [5]:
np.square(arr)

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [6]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [7]:
np.log(arr[1:])

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [8]:
arr1 = np.random.randn(6) # 6 ta elementdan iborat taxminiy qiymatlarga ega massiv
arr1

array([-1.08868966, -2.27675313, -0.21605779, -0.12549705,  0.57715196,
       -0.87007424])

In [9]:
qoldiq, butun = np.modf(arr1) # arr1 ning elementlarini qoldiq va butun qismlarini ikkita massivga ajratib beradi.

In [10]:
print(qoldiq)
print(butun)

[-0.08868966 -0.27675313 -0.21605779 -0.12549705  0.57715196 -0.87007424]
[-1. -2. -0. -0.  0. -0.]


In [11]:
np.sign(arr1) # arr1 massivning elementlari ishoralarini "-1" va "1" larni qaytaradi.

array([-1., -1., -1., -1.,  1., -1.])

isnan massivning elementlarida NaN ma'lumoti bo'lsa True qaytaradi va aksincha esa  False qaytaradi.

In [12]:
arr1

array([-1.08868966, -2.27675313, -0.21605779, -0.12549705,  0.57715196,
       -0.87007424])

In [13]:
np.isnan(arr1)

array([False, False, False, False, False, False])

In [14]:
arr1[0] = np.NaN

In [15]:
np.isnan(arr1)

array([ True, False, False, False, False, False])

Binary funksiyalari (ikkita argument qabul qiluvchi funksiya)

  add, multiply, maximum funksiyalarini ko'rib chiqamiz.

In [16]:
arr2 = np.random.randn(6)
arr2

array([-0.22122193, -1.22168634,  0.10030216, -0.66529549, -1.28774056,
        0.14467765])

In [17]:
arr3 = np.random.randn(6)
arr3

array([ 1.07070984, -0.57803732,  1.31476065, -0.98705459,  0.2129596 ,
        1.03039691])

In [18]:
np.add(arr2, arr3) # arr2 va arr3 ning elementlarini mos ravishda qo'shib beradi.

array([ 0.84948791, -1.79972365,  1.4150628 , -1.65235008, -1.07478096,
        1.17507456])

In [19]:
arr2 + arr3

array([ 0.84948791, -1.79972365,  1.4150628 , -1.65235008, -1.07478096,
        1.17507456])

In [20]:
np.multiply(arr2, arr3) # ikkita mos ravishda teng bo'lgan elementlarni ko'paytirib beradi.

array([-0.2368645 ,  0.70618029,  0.13187333,  0.65668297, -0.27423672,
        0.1490754 ])

In [21]:
np.maximum(arr2, arr3) # ikkita massivning mos qiymatlarini maximumni chiqarib beradi.

array([ 1.07070984, -0.57803732,  1.31476065, -0.66529549,  0.2129596 ,
        1.03039691])

In [22]:
arr2

array([-0.22122193, -1.22168634,  0.10030216, -0.66529549, -1.28774056,
        0.14467765])

In [23]:
arr3

array([ 1.07070984, -0.57803732,  1.31476065, -0.98705459,  0.2129596 ,
        1.03039691])

Mantiqiy shart operatorlarini massiv operator sifatida qo'llash

shart operatori sifatida where dan foydalanish

tassavur qiling bizda ikkita massiv mavjud. xarr va yarr. Agarda shart True ni qaytarsa xarr elementini qabul qilgan aksincha esa yarr elementini qabul qilgan yangi massivni hosil qilsin.

In [24]:
# Massivalar
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5]) # xarr
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5]) # yarr

In [25]:
# shart
cond = np.array([True, False, True, True, False])

In [26]:
# where
result = np.where(cond, xarr, yarr) #cond==True : xarr elementi, cond==False : yarr elementi
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [27]:
arr2 = np.random.randn(4,4)
arr2

array([[-1.31896865, -0.93985633, -0.02884567,  0.62527878],
       [ 2.09125095, -0.20737059,  1.31649891,  0.4611812 ],
       [ 1.11292357,  1.27283718, -0.32436436,  0.80382052],
       [-0.68584712, -0.45875687,  0.84260815,  0.66682365]])

In [30]:
np.where(arr2<0, 2, -2)

array([[ 2,  2,  2, -2],
       [-2,  2, -2, -2],
       [-2, -2,  2, -2],
       [ 2,  2, -2, -2]])

Arifmetik amallar

In [32]:
arr3 = np.arange(6).reshape(2, 3)
arr4 = np.arange(6, 12).reshape(2, 3)
print(arr3)
print(arr4)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [33]:
# massivlarni ko'paytirish
arr3 *arr4

array([[ 0,  7, 16],
       [27, 40, 55]])

In [35]:
# massivlarda bo'lish amallari
arr4[1:] / arr3[1:]

array([[3. , 2.5, 2.2]])

In [39]:
arr4 + arr3

array([[ 6,  8, 10],
       [12, 14, 16]])

In [40]:
# massivlarni ayirish
arr4 - arr3

array([[6, 6, 6],
       [6, 6, 6]])

In [41]:
arr3**2

array([[ 0,  1,  4],
       [ 9, 16, 25]])

In [42]:
np.square(arr3)

array([[ 0,  1,  4],
       [ 9, 16, 25]])

In [43]:
arr3**0.5

array([[0.        , 1.        , 1.41421356],
       [1.73205081, 2.        , 2.23606798]])

Statistik amallar

In [45]:
arr5 = np.random.randn(5, 4)
arr5

array([[-0.33602268,  1.70159883, -0.35773847, -0.01052258],
       [ 0.24500401,  1.06095086,  0.84306543, -1.22990666],
       [ 0.58677572,  0.0775122 , -0.01079396,  0.32885553],
       [-0.74810407,  0.51207953,  0.60507115, -0.29453302],
       [-0.35764229, -1.50798727,  1.28747818,  0.58761187]])

In [53]:
#arr6 = np.random.randint(10, size=(5, 4))
#arr6

array([[9, 4, 0, 0],
       [2, 8, 8, 8],
       [4, 2, 7, 6],
       [7, 6, 6, 0],
       [5, 3, 6, 2]])

In [56]:
arr5.sum() # barcha elementlarni yig'indisini xisoblaydi

2.982752325571681

In [55]:
np.sum(arr5)

2.982752325571681

In [58]:
arr5.sum(axis=1) # elementlarni qatorlar bo'yicha xisoblab beradi.

array([0.99731511, 0.91911364, 0.9823495 , 0.0745136 , 0.00946049])

In [59]:
arr5.sum(axis=0) # elementlarni ustunlar bo'yicha xisoblab beradi.

array([-0.6099893 ,  1.84415415,  2.36708233, -0.61849485])

In [61]:
# mean metodi
data = np.arange(5)
data

array([0, 1, 2, 3, 4])

In [64]:
data.mean() # mean o'rtacha qiymatini xisoblaydi.

2.0

In [63]:
np.mean(data)

2.0

In [65]:
mean = np.sum(data) / len(data)
mean

2.0

In [67]:
len(data)

5

In [68]:
arr5

array([[-0.33602268,  1.70159883, -0.35773847, -0.01052258],
       [ 0.24500401,  1.06095086,  0.84306543, -1.22990666],
       [ 0.58677572,  0.0775122 , -0.01079396,  0.32885553],
       [-0.74810407,  0.51207953,  0.60507115, -0.29453302],
       [-0.35764229, -1.50798727,  1.28747818,  0.58761187]])

In [69]:
arr5.sum()

2.982752325571681

In [70]:
arr5.sum(axis=1)

array([0.99731511, 0.91911364, 0.9823495 , 0.0745136 , 0.00946049])

In [71]:
arr5.sum(axis=0)

array([-0.6099893 ,  1.84415415,  2.36708233, -0.61849485])

In [72]:
np.sum(arr5, axis=1)

array([0.99731511, 0.91911364, 0.9823495 , 0.0745136 , 0.00946049])

In [73]:
np.sum(arr5, axis=0)

array([-0.6099893 ,  1.84415415,  2.36708233, -0.61849485])

In [74]:
data

array([0, 1, 2, 3, 4])

In [76]:
data.cumsum() # cumsum() o'zidan oldingi elementlarni qo'shib o'sha joyga yozadi.

array([ 0,  1,  3,  6, 10])

In [77]:
np.cumsum(data)

array([ 0,  1,  3,  6, 10])

Sorting (tartiblash)

In [80]:
data1 = np.random.rand(7) # rand 0 va 1 oralig'idan element tanlaydi. 
data1

array([0.84658377, 0.01169157, 0.21950298, 0.65356028, 0.07331728,
       0.50762206, 0.93090807])

In [91]:
np.sort(data1) # sort() tartiblaydi.

array([0.01169157, 0.07331728, 0.21950298, 0.50762206, 0.65356028,
       0.84658377, 0.93090807])

In [90]:
data1.sort()
data1

array([0.01169157, 0.07331728, 0.21950298, 0.50762206, 0.65356028,
       0.84658377, 0.93090807])

In [93]:
rev_data = -np.sort(-data)
rev_data

array([4, 3, 2, 1, 0])

In [95]:
data2 = np.random.randn(2, 4)
data2

array([[ 0.84334061, -0.10362095, -1.58938426,  0.60006048],
       [-1.72664448, -0.48875348,  1.47815364,  0.1668915 ]])

In [97]:
row_sorted = np.sort(data2, axis=0)
row_sorted

array([[-1.72664448, -0.48875348, -1.58938426,  0.1668915 ],
       [ 0.84334061, -0.10362095,  1.47815364,  0.60006048]])

In [99]:
data2.sort()
data2

array([[-1.58938426, -0.10362095,  0.60006048,  0.84334061],
       [-1.72664448, -0.48875348,  0.1668915 ,  1.47815364]])

In [100]:
data2

array([[-1.58938426, -0.10362095,  0.60006048,  0.84334061],
       [-1.72664448, -0.48875348,  0.1668915 ,  1.47815364]])

In [101]:
-np.sort(-data2)

array([[ 0.84334061,  0.60006048, -0.10362095, -1.58938426],
       [ 1.47815364,  0.1668915 , -0.48875348, -1.72664448]])

In [103]:
names = np.array(['ali', 'vali', 'nosir', 'aziz', 'o\'tkir', 'asil', 'murod', 'nazir', 'vali', 'asil'])
inst = np.array([3, 3, 3, 4, 5, 5, 6, 8, 9, 9])
names

array(['ali', 'vali', 'nosir', 'aziz', "o'tkir", 'asil', 'murod', 'nazir',
       'vali', 'asil'], dtype='<U6')

In [105]:
np.unique(names) # unique pythondai set funksiyasi bn bir xil yani takrorlanmas elemntni qaytaradi va alfabit bn tartiblaydi.

array(['ali', 'asil', 'aziz', 'murod', 'nazir', 'nosir', "o'tkir", 'vali'],
      dtype='<U6')

In [108]:
set(inst)

{3, 4, 5, 6, 8, 9}

In [117]:
num1 = np.random.randint(10, size=6)
num1

array([0, 2, 4, 7, 7, 4])

In [118]:
num2 = np.random.randint(10, size=6)
num2

array([2, 0, 6, 3, 2, 7])

In [119]:
check =  np.in1d(num1,num2) # in1d num2 nin ichida num1 elementlari bor bo'lsa True yo'q bo'lsa False qaytaradi.
check

array([ True,  True, False,  True,  True, False])

In [120]:
names

array(['ali', 'vali', 'nosir', 'aziz', "o'tkir", 'asil', 'murod', 'nazir',
       'vali', 'asil'], dtype='<U6')

In [121]:
names2 = np.array(['ali', 'bobir', 'qosim', 'asil'])
names2

array(['ali', 'bobir', 'qosim', 'asil'], dtype='<U5')

In [124]:
np.setdiff1d(names2, names)

array(['bobir', 'qosim'], dtype='<U5')

In [1]:
import numpy as np

In [2]:
arr7 = np.arange(10)
arr7

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.save("data", arr7) # save() bitta arrayni saqlaydi.

In [5]:
arr_7 = np.load("data.npy")
arr_7

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
arr8 = np.arange(20)
arr8

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [13]:
np.savez('arrays', a=arr_7, b=arr8)

In [15]:
arrays = np.load('arrays.npz')
arrays['a']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
arrays['b']

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [20]:
from numpy.lib.npyio import savez_compressed
np.savez_compressed("array_compressed", a=arr7, b=arr8)

In [22]:
array_compres = np.load("array_compressed.npz")

In [23]:
array_compres['b']

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [26]:
x = np.arange(6).reshape(2, 3)
x

array([[0, 1, 2],
       [3, 4, 5]])

In [28]:
y = np.random.randint(10, size=(3, 2))
y

array([[1, 0],
       [2, 9],
       [8, 6]])

In [29]:
x.dot(y) #dot x ni y ga ko'paytirish 

array([[18, 21],
       [51, 66]])

In [31]:
np.dot(x,y) #dot x ni y ga ko'paytirish 

array([[18, 21],
       [51, 66]])

In [30]:
y.dot(x) # y ni x ga ko'paytish

array([[ 0,  1,  2],
       [27, 38, 49],
       [18, 32, 46]])

In [32]:
np.dot(y,x) # y ni x ga ko'paytish


array([[ 0,  1,  2],
       [27, 38, 49],
       [18, 32, 46]])